name: Supabase Keep Alive

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          # This requests 1 row from the cars table to keep the project active
          curl -f -X GET 'https://pzjkueabaclfimqmylat.supabase.co/rest/v1/cars?select=id&limit=1' \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
